
import React, { useState, useEffect, useMemo } from 'react';
import { Card, Button, Input, Select, Modal, Badge, Textarea, ConfirmationDialog } from '../components/UI';
import { 
  Plus, Printer, Lock, CreditCard, 
  Wallet, FileText, CheckCircle, Trash2,
  ChevronLeft, ChevronRight, Search, Filter, Calendar,
  Landmark, ArrowUpRight, ArrowDownRight, RefreshCcw, Coins, PieChart as PieChartIcon
} from 'lucide-react';
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, Legend, ResponsiveContainer, PieChart, Pie, Cell
} from 'recharts';
import { api } from '../services/api';
import { Bill, Patient, Appointment, PaymentMethod, TaxRate, Transaction, InsuranceProvider } from '../types';
import { hasPermission, Permissions } from '../utils/rbac';
import { useTranslation } from '../context/TranslationContext';
import { useAuth } from '../context/AuthContext';

const CHART_COLORS = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', '#ec4899', '#06b6d4'];

export const Billing = () => {
  const { t, language } = useTranslation();
  const [activeTab, setActiveTab] = useState<'invoices' | 'treasury'>('invoices');
  const [bills, setBills] = useState<Bill[]>([]);
  const [patients, setPatients] = useState<Patient[]>([]);
  const [paymentMethods, setPaymentMethods] = useState<PaymentMethod[]>([]);
  const [taxRates, setTaxRates] = useState<TaxRate[]>([]);
  const [catalogItems, setCatalogItems] = useState<{label: string, cost: number}[]>([]);
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [insuranceProviders, setInsuranceProviders] = useState<InsuranceProvider[]>([]);
  
  const [loading, setLoading] = useState(true);
  const [isProcessing, setIsProcessing] = useState(false);
  const { user: currentUser } = useAuth();

  // Pagination & Filtering State
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(10);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterType, setFilterType] = useState('all');
  const [dateRange, setDateRange] = useState({ start: '', end: '' });

  // Separate Treasury Filters
  const [treasurySearch, setTreasurySearch] = useState('');
  const [treasuryFilter, setTreasuryFilter] = useState('all');
  const [treasuryDate, setTreasuryDate] = useState({ start: '', end: '' });
  const [treasuryPage, setTreasuryPage] = useState(1);

  // Stats
  const [stats, setStats] = useState({
    totalRevenue: 0,
    pendingAmount: 0,
    paidInvoices: 0,
    revenueByType: [] as {name: string, value: number}[]
  });

  // Treasury Stats
  const [treasuryStats, setTreasuryStats] = useState({
    income: 0,
    expenses: 0,
    net: 0
  });

  // Modals
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [isPaymentModalOpen, setIsPaymentModalOpen] = useState(false);
  const [isExpenseModalOpen, setIsExpenseModalOpen] = useState(false);
  const [isRefundModalOpen, setIsRefundModalOpen] = useState(false);
  
  // Confirmation Dialog
  const [confirmState, setConfirmState] = useState<{
    isOpen: boolean;
    title: string;
    message: string;
    action: () => void;
    type?: 'danger' | 'warning' | 'info';
  }>({ isOpen: false, title: '', message: '', action: () => {} });

  const [selectedBill, setSelectedBill] = useState<Bill | null>(null); // For Invoice View
  const [payingBill, setPayingBill] = useState<Bill | null>(null); // For Payment Action
  const [refundingBill, setRefundingBill] = useState<Bill | null>(null); // For Refund Action

  // Create Invoice Form
  const [createForm, setCreateForm] = useState({
    patientId: '',
    items: [{ description: '', amount: '' }],
    selectedTaxId: ''
  });

  // Payment Form State
  const [paymentForm, setPaymentForm] = useState({
    amount: '',
    method: '', // Dynamic
    date: new Date().toISOString().split('T')[0],
    notes: '',
    // Insurance specific
    insuranceProvider: '',
    policyNumber: '',
    expiryDate: '',
    // Transaction specific
    transactionId: ''
  });

  // Refund Form State
  const [refundForm, setRefundForm] = useState({
    amount: '',
    method: 'Cash',
    reason: 'Service Cancelled',
    date: new Date().toISOString().split('T')[0],
    customReason: ''
  });

  // Expense Form State
  const [expenseForm, setExpenseForm] = useState({
    category: 'General',
    amount: '',
    method: 'Cash',
    date: new Date().toISOString().split('T')[0],
    description: ''
  });

    // --- Helper to derive Bill Type ---
  const getBillType = (bill: Bill): string => {
    // Scan items to determine type based on descriptions generated by backend controllers
    const desc = bill.items?.map(i => i.description.toLowerCase()).join(' ') || '';
    
    if (desc.includes('admission') || desc.includes('accommodation') || desc.includes('deposit')) return 'Admission';
    if (desc.includes('surgery') || desc.includes('operation')) return 'Operation';
    if (desc.includes('lab') || desc.includes('test')) return 'Lab Test';
    if (desc.includes('appointment') || desc.includes('consultation') || desc.includes('follow-up')) return 'Appointment';
    if (desc.includes('service') || desc.includes('procedure') || desc.includes('dressing') || desc.includes('injection')) return 'Procedure';
    
    return 'General';
  };

  const loadData = async () => {
    setLoading(true);
    
    // Helper to catch errors per request so one failure doesn't break the whole page
    const safeFetch = async (promise: Promise<any>, fallback: any) => {
        try {
            return await promise;
        } catch (e) {
            console.warn('Non-critical data fetch failed:', e);
            return fallback;
        }
    };

    try {
      const [b, p, pm, taxes, labs, services, trans, ins] = await Promise.all([
        safeFetch(api.getBills(), []), 
        safeFetch(api.getPatients(), []),
        safeFetch(api.getPaymentMethods(), []),
        safeFetch(api.getTaxRates(), []),
        safeFetch(api.getLabTests(), []),
        safeFetch(api.getNurseServices(), []),
        safeFetch(api.getTransactions(), []),
        safeFetch(api.getInsuranceProviders(), [])
      ]);
      setBills(Array.isArray(b) ? b : []);
      setPatients(Array.isArray(p) ? p : []);
      setPaymentMethods(Array.isArray(pm) ? pm : []);
      setTaxRates(Array.isArray(taxes) ? taxes : []);
      setTransactions(Array.isArray(trans) ? trans : []);
      setInsuranceProviders(Array.isArray(ins) ? ins : []);

      // Build Catalog
      const catalog = [
        ...(Array.isArray(labs) ? labs.map((l: any) => ({ label: `Lab: ${l.name_en}`, cost: l.cost })) : []),
        ...(Array.isArray(services) ? services.map((s: any) => ({ label: `Service: ${s.name_en}`, cost: s.cost })) : [])
      ];
      setCatalogItems(catalog);

      // Calculate Invoice Stats
      const billsArr = Array.isArray(b) ? b : [];
      const total = billsArr.reduce((acc: number, curr: Bill) => acc + (curr.paidAmount || 0), 0);
      const pending = billsArr.reduce((acc: number, curr: Bill) => acc + ((curr.totalAmount || 0) - (curr.paidAmount || 0)), 0);
      const paidCount = billsArr.filter((x: Bill) => x.status === 'paid').length;

      const revenueByTypeMap: Record<string, number> = {};
      billsArr.forEach((bill: Bill) => {
        const type = getBillType(bill);
        revenueByTypeMap[type] = (revenueByTypeMap[type] || 0) + bill.paidAmount;
      });
      const revenueByType = Object.entries(revenueByTypeMap).map(([name, value]) => ({name, value})).sort((a,b) => b.value - a.value);

      setStats({
        totalRevenue: total,
        pendingAmount: pending,
        paidInvoices: paidCount,
        revenueByType
      });

      // Calculate Treasury Stats
      const transArr = Array.isArray(trans) ? trans : [];
      const income = transArr.filter((tx: any) => tx.type === 'income').reduce((sum: number, tx: any) => sum + tx.amount, 0);
      const expense = transArr.filter((tx: any) => tx.type === 'expense').reduce((sum: number, tx: any) => sum + tx.amount, 0);
      setTreasuryStats({ income, expenses: expense, net: income - expense });

    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  // --- Handlers ---

  const handleAddItem = () => {
    setCreateForm({
      ...createForm,
      items: [...createForm.items, { description: '', amount: '' }]
    });
  };

  const handleRemoveItem = (index: number) => {
    const newItems = createForm.items.filter((_, i) => i !== index);
    setCreateForm({ ...createForm, items: newItems });
  };

  const handleItemChange = (index: number, field: 'description' | 'amount', value: string) => {
    const newItems = [...createForm.items];
    newItems[index] = { ...newItems[index], [field]: value };
    setCreateForm({ ...createForm, items: newItems });
  };

  const handleCatalogSelect = (index: number, value: string) => {
    if (!value) return;
    const item = catalogItems.find(i => i.label === value);
    if (item) {
        const newItems = [...createForm.items];
        newItems[index] = { description: item.label, amount: item.cost.toString() };
        setCreateForm({ ...createForm, items: newItems });
    }
  };

  const handleCreateSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const patient = patients.find(p => p.id === parseInt(createForm.patientId));
    
    // Filter out empty rows and format
    let formattedItems = createForm.items
      .filter(i => i.description && i.amount)
      .map(i => ({ description: i.description, amount: parseFloat(i.amount) }));

    if (patient && formattedItems.length > 0) {
      setIsProcessing(true);
      let total = formattedItems.reduce((sum, i) => sum + i.amount, 0);
      
      // Apply Tax if selected
      if (createForm.selectedTaxId) {
          const tax = taxRates.find(t => t.id === parseInt(createForm.selectedTaxId));
          if (tax) {
              const taxAmount = (total * tax.rate) / 100;
              formattedItems.push({
                  description: `Tax: ${tax.name_en} (${tax.rate}%)`,
                  amount: parseFloat(taxAmount.toFixed(2))
              });
              total += taxAmount;
          }
      }

      try {
        await api.createBill({
          patientId: patient.id,
          patientName: patient.fullName,
          totalAmount: total,
          date: new Date().toISOString().split('T')[0],
          items: formattedItems
        });
        
        setIsCreateModalOpen(false);
        setCreateForm({ patientId: '', items: [{ description: '', amount: '' }], selectedTaxId: '' });
        loadData();
      } catch(e) {
        console.error(e);
      } finally {
        setIsProcessing(false);
      }
    }
  };

  const openPaymentModal = (bill: Bill) => {
    setPayingBill(bill);
    const patient = patients.find(p => p.id === bill.patientId);
    
    // Default to remaining balance
    const remaining = bill.totalAmount - (bill.paidAmount || 0);
    
    // Smart Pre-fill: Check insurance
    const hasInsurance = patient?.hasInsurance;
    
    // Try to find default method
    // If paymentMethods is loaded, use logic. If fallback (empty), default to Cash or Insurance.
    let defaultMethod = 'Cash';
    if (paymentMethods.length > 0) {
        defaultMethod = hasInsurance ? 'Insurance' : paymentMethods[0].name_en;
    } else {
        defaultMethod = hasInsurance ? 'Insurance' : 'Cash';
    }

    setPaymentForm({ 
        amount: remaining.toString(), 
        method: defaultMethod,
        date: new Date().toISOString().split('T')[0],
        notes: '',
        transactionId: '',
        insuranceProvider: hasInsurance ? patient?.insuranceDetails?.provider || '' : '',
        policyNumber: hasInsurance ? patient?.insuranceDetails?.policyNumber || '' : '',
        expiryDate: hasInsurance ? patient?.insuranceDetails?.expiryDate || '' : ''
    });
    setIsPaymentModalOpen(true);
  };

  const handlePaymentSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!payingBill) return;
    setIsProcessing(true);

    // Construct Payment Payload
    const payload: any = {
        amount: parseFloat(paymentForm.amount),
        method: paymentForm.method,
        date: paymentForm.date,
        details: { notes: paymentForm.notes }
    };

    if (paymentForm.method === 'Insurance') {
        payload.details = {
            ...payload.details,
            provider: paymentForm.insuranceProvider,
            policyNumber: paymentForm.policyNumber,
            expiryDate: paymentForm.expiryDate
        };
    } else if (paymentForm.method !== 'Cash') {
        payload.details = {
            ...payload.details,
            transactionId: paymentForm.transactionId
        };
    }

    try {
      await api.recordPayment(payingBill.id, payload);
      setIsPaymentModalOpen(false);
      setPayingBill(null);
      loadData();
    } catch (e) {
      alert('Payment failed');
    } finally {
      setIsProcessing(false);
    }
  };

  const openRefundModal = (bill: Bill) => {
    setRefundingBill(bill);
    // Default to fully paid amount
    setRefundForm({
        amount: bill.paidAmount.toString(),
        method: 'Cash',
        reason: 'Service Cancelled',
        date: new Date().toISOString().split('T')[0],
        customReason: ''
    });
    setIsRefundModalOpen(true);
  };

  const handleRefundSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!refundingBill) return;
    setIsProcessing(true);

    try {
        const finalReason = refundForm.reason === 'Other' ? refundForm.customReason : refundForm.reason;
        
        await api.processRefund(refundingBill.id, {
            amount: parseFloat(refundForm.amount),
            method: refundForm.method,
            reason: finalReason,
            date: refundForm.date
        });
        setIsRefundModalOpen(false);
        setRefundingBill(null);
        loadData();
    } catch (e) {
        alert('Refund failed');
    } finally {
        setIsProcessing(false);
    }
  };

  const handleCancelService = (bill: Bill) => {
    setConfirmState({
      isOpen: true,
      title: t('billing_cancel_dialog_title'),
      message: t('billing_cancel_dialog_message'),
      type: 'danger',
      action: async () => {
        setIsProcessing(true);
        try {
          await api.cancelService(bill.id); 
          loadData();
        } catch (e) {
          console.error(e);
          alert('Failed to cancel service.');
        } finally {
          setIsProcessing(false);
        }
      }
    });
  };

  const handleExpenseSubmit = async (e: React.FormEvent) => {
      e.preventDefault();
      setIsProcessing(true);
      try {
          await api.addExpense({
              ...expenseForm,
              amount: parseFloat(expenseForm.amount)
          });
          setIsExpenseModalOpen(false);
          setExpenseForm({ category: 'General', amount: '', method: 'Cash', date: new Date().toISOString().split('T')[0], description: '' });
          loadData();
      } catch(e) {
          alert('Failed to add expense');
      } finally {
          setIsProcessing(false);
      }
  };

  const getTypeColor = (type: string) => {
    switch (type) {
      case 'Admission': return 'orange';
      case 'Operation': return 'red';
      case 'Lab Test': return 'purple';
      case 'Appointment': return 'blue';
      case 'Procedure': return 'cyan';
      default: return 'gray';
    }
  };

  const translateBillType = (type: string) => {
      switch(type) {
          case 'Admission': return t('billing_type_admission');
          case 'Operation': return t('billing_type_operation');
          case 'Lab Test': return t('billing_type_lab');
          case 'Appointment': return t('billing_type_appointment');
          case 'Procedure': return t('billing_type_procedure');
          default: return t('billing_type_general');
      }
  };

  // --- Filtering & Pagination Logic (Bills) ---
  const filteredBills = useMemo(() => {
    return bills.filter(bill => {
      const matchesSearch = 
        bill.patientName.toLowerCase().includes(searchTerm.toLowerCase()) ||
        bill.billNumber.toLowerCase().includes(searchTerm.toLowerCase());
      
      const billType = getBillType(bill);
      const matchesType = filterType === 'all' || billType === filterType;

      let matchesDate = true;
      if (dateRange.start) {
        matchesDate = matchesDate && new Date(bill.date) >= new Date(dateRange.start);
      }
      if (dateRange.end) {
        const endDate = new Date(dateRange.end);
        endDate.setHours(23, 59, 59, 999);
        matchesDate = matchesDate && new Date(bill.date) <= endDate;
      }

      return matchesSearch && matchesType && matchesDate;
    });
  }, [bills, searchTerm, filterType, dateRange]);

  const totalPages = Math.ceil(filteredBills.length / itemsPerPage);
  const paginatedBills = filteredBills.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);

  // --- Filtering & Pagination Logic (Treasury) ---
  const filteredTransactions = useMemo(() => {
    return transactions.filter(t => {
        const matchesSearch = 
            (t.description && t.description.toLowerCase().includes(treasurySearch.toLowerCase())) ||
            (t.category && t.category.toLowerCase().includes(treasurySearch.toLowerCase()));
        
        const matchesType = treasuryFilter === 'all' || t.type === treasuryFilter;

        let matchesDate = true;
        if (treasuryDate.start) {
            matchesDate = matchesDate && new Date(t.date) >= new Date(treasuryDate.start);
        }
        if (treasuryDate.end) {
            const endDate = new Date(treasuryDate.end);
            endDate.setHours(23, 59, 59, 999);
            matchesDate = matchesDate && new Date(t.date) <= endDate;
        }

        return matchesSearch && matchesType && matchesDate;
    });
  }, [transactions, treasurySearch, treasuryFilter, treasuryDate]);

  // Aggregate daily data for chart
  const treasuryChartData = useMemo(() => {
    const dailyMap = new Map<string, {name: string, income: number, expense: number}>();
    
    // Sort transactions by date asc for chart
    const sortedTrans = [...filteredTransactions].sort((a,b) => new Date(a.date).getTime() - new Date(b.date).getTime());
    
    sortedTrans.forEach(tx => {
        const day = new Date(tx.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
        if (!dailyMap.has(day)) {
            dailyMap.set(day, { name: day, income: 0, expense: 0 });
        }
        const entry = dailyMap.get(day)!;
        if (tx.type === 'income') entry.income += tx.amount;
        else entry.expense += tx.amount;
    });

    return Array.from(dailyMap.values());
  }, [filteredTransactions]);

  // Method Breakdown (Income vs Expense per Method)
  const methodStats = useMemo(() => {
    const stats: Record<string, { income: number; expense: number; balance: number }> = {};
    
    // Initialize with config methods to ensure they show up
    paymentMethods.forEach(pm => {
        stats[pm.name_en] = { income: 0, expense: 0, balance: 0 };
    });
    // Ensure Cash exists
    if (!stats['Cash']) stats['Cash'] = { income: 0, expense: 0, balance: 0 };

    filteredTransactions.forEach(tx => {
        const method = tx.method || 'Unknown';
        if (!stats[method]) stats[method] = { income: 0, expense: 0, balance: 0 };
        
        if (tx.type === 'income') {
            stats[method].income += tx.amount;
            stats[method].balance += tx.amount;
        } else {
            stats[method].expense += tx.amount;
            stats[method].balance -= tx.amount;
        }
    });

    return Object.entries(stats)
        .map(([name, data]) => ({ name, ...data }))
        .sort((a, b) => b.balance - a.balance); // Sort by balance desc
  }, [filteredTransactions, paymentMethods]);

  const getMethodIcon = (name: string) => {
      const n = name.toLowerCase();
      if (n.includes('cash')) return Coins;
      if (n.includes('bank') || n.includes('transfer')) return Landmark;
      if (n.includes('card') || n.includes('visa') || n.includes('master')) return CreditCard;
      return Wallet;
  };

  const totalTreasuryPages = Math.ceil(filteredTransactions.length / itemsPerPage);
  const paginatedTransactions = filteredTransactions.slice((treasuryPage - 1) * itemsPerPage, treasuryPage * itemsPerPage);


  // --- Render Helpers ---

  const InvoiceView = ({ bill }: { bill: Bill }) => {
    // Try to find Tax Item
    const taxItem = bill.items.find(i => i.description.toLowerCase().startsWith('tax'));
    const subtotal = bill.items.filter(i => !i.description.toLowerCase().startsWith('tax')).reduce((sum, i) => sum + i.amount, 0);
    const taxAmount = taxItem ? taxItem.amount : 0;
    const hospitalName = localStorage.getItem('hospital_name') || 'AllCare Hospital';
    const [hospitalInfo, setHospitalInfo] = useState<any>({});

    useEffect(() => {
        api.getPublicSettings().then(setHospitalInfo);
    }, []);

    return (
        <div className="p-10 bg-white min-h-[600px] text-slate-800 font-sans" id="invoice-print">
        {/* Header */}
        <div className="flex justify-between items-start border-b-2 border-slate-100 pb-8 mb-8">
            <div className="flex flex-col gap-2">
                <div className="flex items-center gap-3">
                    <div className="bg-primary-600 text-white p-2.5 rounded-xl shadow-lg shadow-primary-500/30">
                        <Wallet size={28}/>
                    </div>
                    <div>
                        <h1 className="text-2xl font-bold text-slate-900 tracking-tight">{t('billing_invoice_title')}</h1>
                        <p className="text-slate-500 font-mono text-sm">#{bill.billNumber}</p>
                    </div>
                </div>
                <div className="flex gap-2 mt-2">
                    <span className={`px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider border ${bill.status === 'paid' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' : bill.status === 'refunded' ? 'bg-purple-50 text-purple-700 border-purple-200' : 'bg-red-50 text-red-700 border-red-200'}`}>
                        {bill.status}
                    </span>
                    <span className="px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider bg-slate-100 text-slate-600 border border-slate-200">
                        {translateBillType(getBillType(bill))}
                    </span>
                </div>
            </div>
            <div className="text-right">
                <h2 className="text-xl font-bold text-primary-600">{hospitalName}</h2>
                <div className="text-sm text-slate-500 mt-2 space-y-1">
                    <p>{hospitalInfo.hospitalAddress || '123 Health Ave, Med City'}</p>
                    <p>contact@allcare.com</p>
                    <p>{hospitalInfo.hospitalPhone || '+1 (555) 012-3456'}</p>
                </div>
            </div>
        </div>

        {/* Client Info Grid */}
        <div className="grid grid-cols-2 gap-8 mb-10 bg-slate-50 p-6 rounded-2xl border border-slate-100">
            <div>
                <p className="text-xs text-slate-400 font-bold uppercase tracking-wider mb-2">{t('billing_invoice_billed_to')}</p>
                <p className="font-bold text-lg text-slate-900">{bill.patientName}</p>
                <p className="text-slate-500 text-sm mt-1">{t('patient_id')}: <span className="font-mono text-slate-600">#{bill.patientId}</span></p>
            </div>
            <div className="text-right">
                <p className="text-xs text-slate-400 font-bold uppercase tracking-wider mb-2">{t('billing_invoice_date')}</p>
                <p className="font-bold text-lg text-slate-900">{new Date(bill.date).toLocaleDateString()}</p>
                <p className="text-slate-500 text-sm mt-1">{new Date(bill.date).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}</p>
            </div>
        </div>

        {/* Line Items */}
        <div className="mb-8">
            <table className="w-full">
                <thead>
                <tr className="border-b border-slate-200">
                    <th className="text-left py-4 px-2 font-bold text-xs text-slate-500 uppercase tracking-wider">{t('billing_invoice_description')} :</th>
                    <th className="text-right py-4 px-2 font-bold text-xs text-slate-500 uppercase tracking-wider">{t('billing_table_header_amount')}</th>
                </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                {bill.items.map((item, i) => (
                    <tr key={i}>
                    <td className="py-4 px-2 text-sm font-medium text-slate-700">{item.description}</td>
                    <td className="py-4 px-2 text-right font-bold text-slate-900 font-mono">${item.amount.toFixed(2)}</td>
                    </tr>
                ))}
                </tbody>
            </table>
        </div>

        {/* Totals */}
        <div className="flex justify-end">
            <div className="w-full max-w-sm space-y-3 bg-slate-50 p-6 rounded-2xl border border-slate-100">
            <div className="flex justify-between text-slate-600 text-sm">
                <span>{t('billing_invoice_subtotal')}</span>
                <span className="font-medium font-mono">${subtotal.toFixed(2)}</span>
            </div>
            {taxAmount > 0 && (
                <div className="flex justify-between text-slate-600 text-sm">
                    <span>{t('billing_invoice_tax')}</span>
                    <span className="font-medium font-mono">${taxAmount.toFixed(2)}</span>
                </div>
            )}
            <div className="h-px bg-slate-200 my-2"></div>
            <div className="flex justify-between text-slate-900 font-bold text-lg">
                <span>{t('billing_invoice_total')}</span>
                <span className="font-mono">${bill.totalAmount.toFixed(2)}</span>
            </div>
            <div className="flex justify-between text-emerald-600 font-bold text-sm">
                <span>{t('billing_invoice_paid')}</span>
                <span className="font-mono">-${(bill.paidAmount || 0).toFixed(2)}</span>
            </div>
            {bill.totalAmount > bill.paidAmount && (
                <div className="flex justify-between text-red-600 font-bold text-xl pt-2 border-t border-slate-200 mt-2">
                    <span>{t('billing_invoice_balance')}</span>
                    <span className="font-mono">${(bill.totalAmount - (bill.paidAmount || 0)).toFixed(2)}</span>
                </div>
            )}
            </div>
        </div>
        </div>
    );
  };

  const canManageBilling = hasPermission(currentUser, Permissions.MANAGE_BILLING);
  const isAccountant = currentUser?.role === 'accountant' || currentUser?.role === 'admin';

  // Logic for Refund/Cancel Button
  // If paid and service active -> Show Cancel (which cancels service).
  // If paid and service cancelled -> Show Refund (financial action).
  const getActionForPaidBill = (bill: Bill) => {
      const isServiceCancelled = bill.serviceStatus === 'cancelled';
      if (!isServiceCancelled) {
          return (
              <Button 
                  size="sm" 
                  variant="danger" 
                  onClick={() => handleCancelService(bill)}
                  disabled={isProcessing}
              >
                  {t('billing_action_cancel_process')}
              </Button>
          );
      } else {
          return (
              <Button 
                  size="sm" 
                  className="bg-purple-600 hover:bg-purple-700 text-white border-none"
                  disabled={!isAccountant} 
                  icon={RefreshCcw}
                  title={!isAccountant ? "Refunds require Accountant role" : ""}
                  onClick={() => isAccountant && openRefundModal(bill)}
              >
                  {t('billing_action_refund')}
              </Button>
          );
      }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white">{t('billing_title')}</h1>
          <p className="text-sm text-slate-500 dark:text-slate-400">{t('billing_subtitle')}</p>
        </div>
      </div>

      {/* Main Tabs */}
      <div className="flex bg-white dark:bg-slate-800 p-1 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 w-fit mb-6">
          {[
              { id: 'invoices', label: t('billing_tab_invoices'), icon: FileText },
              { id: 'treasury', label: t('billing_tab_treasury'), icon: Landmark },
          ].map(tab => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as any)}
                className={`flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-bold transition-all ${activeTab === tab.id ? 'bg-primary-50 dark:bg-primary-900/20 text-primary-700 dark:text-primary-300 shadow-sm' : 'text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200'}`}
              >
                  <tab.icon size={18} />
                  {tab.label}
              </button>
          ))}
      </div>

      {activeTab === 'invoices' && (
        <div className="animate-in fade-in space-y-6">
            {/* Stats Cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <Card>
                    <h4 className="text-xs font-bold text-slate-500 uppercase">{t('billing_stat_revenue')}</h4>
                    <p className="text-3xl font-bold text-emerald-600 mt-2">${stats.totalRevenue.toLocaleString()}</p>
                </Card>
                <Card>
                    <h4 className="text-xs font-bold text-slate-500 uppercase">{t('billing_stat_pending')}</h4>
                    <p className="text-3xl font-bold text-orange-500 mt-2">${stats.pendingAmount.toLocaleString()}</p>
                </Card>
                <Card>
                    <h4 className="text-xs font-bold text-slate-500 uppercase">{t('billing_stat_paid')}</h4>
                    <p className="text-3xl font-bold text-slate-800 dark:text-white mt-2">{stats.paidInvoices}</p>
                </Card>
            </div>
            
            {/* Revenue by Type Chart */}
            <Card title="Revenue by Service Type">
              <div className="h-80 w-full flex flex-col md:flex-row items-center gap-6">
                <div className="w-full md:w-1/2 h-full">
                  <ResponsiveContainer>
                    <PieChart>
                      <Pie
                        data={stats.revenueByType}
                        cx="50%"
                        cy="50%"
                        innerRadius={80}
                        outerRadius={110}
                        paddingAngle={5}
                        dataKey="value"
                        nameKey="name"
                      >
                        {stats.revenueByType.map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={CHART_COLORS[index % CHART_COLORS.length]} className="focus:outline-none ring-0"/>
                        ))}
                      </Pie>
                      <RechartsTooltip formatter={(value) => `$${Number(value).toLocaleString()}`} />
                    </PieChart>
                  </ResponsiveContainer>
                </div>
                <div className="w-full md:w-1/2 space-y-3">
                  <h4 className="text-sm font-bold text-slate-500 dark:text-slate-400 mb-2 border-b border-slate-200 dark:border-slate-700 pb-2">Legend</h4>
                  {stats.revenueByType.map((entry, index) => (
                    <div key={`legend-${index}`} className="flex items-center justify-between text-sm hover:bg-slate-50 dark:hover:bg-slate-700/50 p-2 rounded-lg">
                      <div className="flex items-center gap-3">
                        <div
                          className="w-4 h-4 rounded-md"
                          style={{ backgroundColor: CHART_COLORS[index % CHART_COLORS.length] }}
                        />
                        <span className="text-slate-600 dark:text-slate-300 font-medium">{translateBillType(entry.name)}</span>
                      </div>
                      <span className="font-bold text-slate-800 dark:text-white font-mono">${entry.value.toLocaleString()}</span>
                    </div>
                  ))}
                </div>
              </div>
            </Card>

            <Card className="!p-0 border border-slate-200 dark:border-slate-700 shadow-sm overflow-hidden z-10">
                <div className="p-4 border-b border-slate-200 dark:border-slate-700 flex flex-col md:flex-row gap-4 items-start md:items-center justify-between">
                  <div className="flex flex-col sm:flex-row gap-2 w-full md:w-auto">
                    <div className="relative w-full sm:w-64">
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 w-4 h-4" />
                        <input type="text" placeholder={t('billing_search_placeholder')} className="pl-9 pr-4 py-2 w-full rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-800 text-sm" value={searchTerm} onChange={e => { setSearchTerm(e.target.value); setCurrentPage(1); }}/>
                    </div>
                    <div className="relative w-full sm:w-auto">
                        <Filter className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 w-4 h-4 pointer-events-none" />
                        <select className="pl-9 pr-8 py-2 w-full rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-800 text-sm focus:ring-2 focus:ring-primary-500 outline-none appearance-none cursor-pointer" value={filterType} onChange={e => { setFilterType(e.target.value); setCurrentPage(1); }}>
                            <option value="all">{t('patients_filter_type_all')}</option>
                            <option value="Appointment">{t('billing_type_appointment')}</option>
                            <option value="Lab Test">{t('billing_type_lab')}</option>
                            <option value="Admission">{t('billing_type_admission')}</option>
                            <option value="Operation">{t('billing_type_operation')}</option>
                            <option value="Procedure">{t('billing_type_procedure')}</option>
                            <option value="General">{t('billing_type_general')}</option>
                        </select>
                    </div>
                  </div>
                  {canManageBilling && (<Button onClick={() => setIsCreateModalOpen(true)} icon={Plus}>{t('billing_create_invoice_button')}</Button>)}
                </div>

                {loading ? <div className="text-center py-10 text-slate-500">{t('billing_table_loading')}</div> :
                 paginatedBills.length === 0 ? <div className="text-center py-10 text-slate-500">{t('billing_table_empty')}</div> :
                 (
                    <div className="overflow-x-auto">
                      <table className="min-w-full divide-y divide-slate-200 dark:divide-slate-700">
                        <thead className="bg-slate-50 dark:bg-slate-900">
                          <tr>
                            <th className="px-6 py-3 text-left text-xs font-bold text-slate-500 uppercase tracking-wider">{t('billing_table_header_info')}</th>
                            <th className="px-6 py-3 text-left text-xs font-bold text-slate-500 uppercase tracking-wider">{t('patients_table_header_patient')}</th>
                            <th className="px-6 py-3 text-left text-xs font-bold text-slate-500 uppercase tracking-wider">{t('billing_table_header_status')}</th>
                            <th className="px-6 py-3 text-left text-xs font-bold text-slate-500 uppercase tracking-wider">{t('billing_table_header_paid_progress')}</th>
                            <th className="px-6 py-3 text-right text-xs font-bold text-slate-500 uppercase tracking-wider">{t('billing_table_header_amount')}</th>
                            <th className="px-6 py-3 text-right text-xs font-bold text-slate-500 uppercase tracking-wider">{t('billing_table_header_actions')}</th>
                          </tr>
                        </thead>
                        <tbody className="bg-white dark:bg-slate-800 divide-y divide-slate-200 dark:divide-slate-700">
                          {paginatedBills.map(bill => {
                            const paidPercent = bill.totalAmount > 0 ? (bill.paidAmount / bill.totalAmount) * 100 : 0;
                            return (
                              <tr key={bill.id}>
                                <td className="px-6 py-4 whitespace-nowrap">
                                    <div className="font-bold text-slate-800 dark:text-white">{bill.billNumber}</div>
                                    <div className="text-sm text-slate-500">{new Date(bill.date).toLocaleDateString()}</div>
                                </td>
                                <td className="px-6 py-4 whitespace-nowrap">
                                    <div className="text-sm font-medium text-slate-900 dark:text-white">{bill.patientName}</div>
                                    <div className="text-xs text-slate-500 font-mono">ID: {bill.patientId}</div>
                                </td>
                                <td className="px-6 py-4 whitespace-nowrap">
                                    <div className="flex flex-col gap-1">
                                        <Badge color={bill.status === 'paid' ? 'green' : bill.status === 'partial' ? 'yellow' : 'red'}>{bill.status}</Badge>
                                        <Badge color={getTypeColor(getBillType(bill)) as any}>{translateBillType(getBillType(bill))}</Badge>
                                    </div>
                                </td>
                                <td className="px-6 py-4 whitespace-nowrap min-w-[150px]">
                                    <div className="w-full bg-slate-100 dark:bg-slate-700 rounded-full h-2.5">
                                        <div className="bg-gradient-to-r from-emerald-400 to-green-500 h-2.5 rounded-full" style={{ width: `${paidPercent}%` }}></div>
                                    </div>
                                    <p className="text-right text-xs mt-1 text-emerald-600 font-medium">
                                        ${bill.paidAmount.toLocaleString()} / ${bill.totalAmount.toLocaleString()}
                                    </p>
                                </td>
                                <td className="px-6 py-4 whitespace-nowrap text-right font-mono font-bold text-slate-800 dark:text-white">
                                    ${bill.totalAmount.toLocaleString()}
                                </td>
                                <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <div className="flex justify-end gap-2">
                                        <Button size="sm" variant="outline" icon={FileText} onClick={() => setSelectedBill(bill)}>{t('billing_action_view_invoice')}</Button>
                                        {canManageBilling && (
                                            <>
                                                {(bill.status === 'pending' || bill.status === 'partial') && (
                                                    <Button size="sm" onClick={() => openPaymentModal(bill)}>{t('billing_action_pay')}</Button>
                                                )}
                                                {bill.status === 'paid' && getActionForPaidBill(bill)}
                                            </>
                                        )}
                                    </div>
                                </td>
                              </tr>
                            );
                          })}
                        </tbody>
                      </table>
                    </div>
                 )
                }
                
                {!loading && (
                    <div className="flex justify-between items-center p-4 border-t border-slate-200 dark:border-slate-700">
                        <span className="text-sm text-slate-500">{t('patients_pagination_showing')} {paginatedBills.length} {t('patients_pagination_of')} {filteredBills.length}</span>
                        <div className="flex gap-2">
                            <Button size="sm" variant="secondary" onClick={() => setCurrentPage(p => Math.max(1, p - 1))} disabled={currentPage === 1} icon={ChevronLeft}>Prev</Button>
                            <Button size="sm" variant="secondary" onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))} disabled={currentPage === totalPages} icon={ChevronRight}>Next</Button>
                        </div>
                    </div>
                )}

            </Card>
        </div>
      )}

      {/* ... Treasury Tab ... */}
      {activeTab === 'treasury' && (
          <div className="space-y-6 animate-in fade-in">
              <div className="flex justify-end">
                  <Button onClick={() => setIsExpenseModalOpen(true)} icon={Plus} variant="secondary">{t('billing_record_expense_button')}</Button>
              </div>

              {/* Treasury Stats */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  <Card>
                    <h4 className="text-xs font-bold text-slate-500 uppercase">{t('billing_treasury_income')}</h4>
                    <p className="text-3xl font-bold text-green-600 mt-2 flex items-center gap-2"><ArrowUpRight size={24}/> ${treasuryStats.income.toLocaleString()}</p>
                  </Card>
                  <Card>
                    <h4 className="text-xs font-bold text-slate-500 uppercase">{t('billing_treasury_expenses')}</h4>
                    <p className="text-3xl font-bold text-red-500 mt-2 flex items-center gap-2"><ArrowDownRight size={24}/> ${treasuryStats.expenses.toLocaleString()}</p>
                  </Card>
                  <Card>
                    <h4 className="text-xs font-bold text-slate-500 uppercase">{t('billing_treasury_net')}</h4>
                    <p className={`text-3xl font-bold mt-2 ${treasuryStats.net >= 0 ? 'text-blue-600' : 'text-red-600'}`}>${treasuryStats.net.toLocaleString()}</p>
                  </Card>
              </div>

              {/* Charts Row */}
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                  {/* Cash Flow Bar Chart */}
                  <div className="h-96 w-full bg-white dark:bg-slate-800 rounded-xl p-4 border border-slate-200 dark:border-slate-700 shadow-sm overflow-hidden">
                      <h3 className="font-bold text-slate-800 dark:text-white mb-4">{t('billing_treasury_chart_flow')}</h3>
                      <ResponsiveContainer width="100%" height="100%">
                        <BarChart data={treasuryChartData}>
                            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" className="dark:stroke-slate-700" />
                            <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill: '#64748b', fontSize: 12}} />
                            <YAxis axisLine={false} tickLine={false} tick={{fill: '#64748b', fontSize: 12}} />
                            <RechartsTooltip 
                                cursor={{fill: 'transparent'}}
                                contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 12px rgba(0,0,0,0.1)', backgroundColor: '#fff', color: '#1e293b' }} 
                            />
                            <Legend />
                            <Bar dataKey="income" name={t('billing_treasury_type_income')} fill="#10b981" radius={[4, 4, 0, 0]} barSize={20} />
                            <Bar dataKey="expense" name={t('billing_treasury_type_expense')} fill="#ef4444" radius={[4, 4, 0, 0]} barSize={20} />
                        </BarChart>
                      </ResponsiveContainer>
                  </div>

                  {/* Method Holdings */}
                  <div className="h-96 w-full bg-white dark:bg-slate-800 rounded-xl p-0 border border-slate-200 dark:border-slate-700 shadow-sm flex flex-col overflow-hidden">
                      <div className="p-4 border-b border-slate-100 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-900/50">
                          <h3 className="font-bold text-slate-800 dark:text-white">{t('billing_treasury_holdings')}</h3>
                          <p className="text-xs text-slate-500">{t('billing_treasury_holdings_subtitle')}</p>
                      </div>
                      <div className="flex-1 overflow-y-auto p-4 space-y-3 custom-scrollbar">
                          {methodStats.map((item) => {
                              const Icon = getMethodIcon(item.name);
                              return (
                                  <div key={item.name} className="flex items-center gap-4 p-3 rounded-xl border border-slate-100 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/20">
                                      <div className={`p-3 rounded-full ${item.balance >= 0 ? 'bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400' : 'bg-red-100 text-red-600'}`}>
                                          <Icon size={20} />
                                      </div>
                                      <div className="flex-1 min-w-0">
                                          <div className="flex justify-between items-center mb-1">
                                              <h4 className="font-bold text-slate-700 dark:text-slate-200 truncate">{item.name}</h4>
                                              <span className={`font-mono font-bold ${item.balance >= 0 ? 'text-slate-900 dark:text-white' : 'text-red-500'}`}>
                                                  ${item.balance.toLocaleString()}
                                              </span>
                                          </div>
                                          <div className="flex items-center gap-3 text-xs">
                                              <span className="flex items-center gap-1 text-emerald-600 bg-emerald-50 dark:bg-emerald-900/20 px-1.5 py-0.5 rounded">
                                                  <ArrowUpRight size={10}/> ${item.income.toLocaleString()}
                                              </span>
                                              <span className="flex items-center gap-1 text-red-600 bg-red-50 dark:bg-red-900/20 px-1.5 py-0.5 rounded">
                                                  <ArrowDownRight size={10}/> ${item.expense.toLocaleString()}
                                              </span>
                                          </div>
                                      </div>
                                  </div>
                              );
                          })}
                      </div>
                  </div>
              </div>

              <Card className="!p-0 border border-slate-200 dark:border-slate-700 shadow-sm overflow-hidden">
                  <div className="p-4 bg-slate-50 dark:bg-slate-900 border-b border-slate-200 dark:border-slate-700 flex flex-col md:flex-row gap-4 items-center">
                      <div className="flex items-center gap-2 flex-1">
                          <Landmark size={18} className="text-slate-500"/> 
                          <h3 className="font-bold text-slate-800 dark:text-white">{t('billing_treasury_transactions')}</h3>
                      </div>
                      <div className="flex gap-2">
                          <input 
                            type="text" 
                            placeholder={t('search_placeholder')} 
                            className="px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-800 text-sm"
                            value={treasurySearch}
                            onChange={(e) => setTreasurySearch(e.target.value)}
                          />
                          <select 
                            className="px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-800 text-sm"
                            value={treasuryFilter}
                            onChange={(e) => setTreasuryFilter(e.target.value)}
                          >
                              <option value="all">{t('patients_filter_type_all')}</option>
                              <option value="income">{t('billing_treasury_type_income')}</option>
                              <option value="expense">{t('billing_treasury_type_expense')}</option>
                          </select>
                          <input 
                            type="date" 
                            className="px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-800 text-sm"
                            value={treasuryDate.start}
                            onChange={(e) => setTreasuryDate({...treasuryDate, start: e.target.value})}
                          />
                      </div>
                  </div>
                  <div className="overflow-x-auto">
                      <table className="min-w-full divide-y divide-slate-200 dark:divide-slate-700">
                          <thead className="bg-white dark:bg-slate-900">
                              <tr>
                                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-500 uppercase">{t('date')}</th>
                                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-500 uppercase">{t('appointments_form_type')}</th>
                                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-500 uppercase">{t('billing_treasury_table_category')}</th>
                                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-500 uppercase">{t('billing_treasury_table_description')}</th>
                                  <th className="px-6 py-3 text-left text-xs font-bold text-slate-500 uppercase">{t('billing_treasury_table_method')}</th>
                                  <th className="px-6 py-3 text-right text-xs font-bold text-slate-500 uppercase">{t('billing_table_header_amount')}</th>
                              </tr>
                          </thead>
                          <tbody className="divide-y divide-slate-100 dark:divide-slate-700 bg-white dark:bg-slate-800">
                              {paginatedTransactions.map((tx) => (
                                  <tr key={tx.id}>
                                      <td className="px-6 py-3 text-sm text-slate-600 dark:text-slate-300">{new Date(tx.date).toLocaleDateString()}</td>
                                      <td className="px-6 py-3">
                                          <Badge color={tx.type === 'income' ? 'green' : 'red'}>{tx.type === 'income' ? t('billing_treasury_type_income') : t('billing_treasury_type_expense')}</Badge>
                                      </td>
                                      <td className="px-6 py-3 text-sm font-medium">{tx.category || '-'}</td>
                                      <td className="px-6 py-3 text-sm text-slate-500">{tx.description}</td>
                                      <td className="px-6 py-3 text-sm">{tx.method}</td>
                                      <td className={`px-6 py-3 text-sm font-bold text-right ${tx.type === 'income' ? 'text-green-600' : 'text-red-600'}`}>
                                          {tx.type === 'income' ? '+' : '-'}${tx.amount.toLocaleString()}
                                      </td>
                                  </tr>
                              ))}
                          </tbody>
                      </table>
                  </div>
                  {/* Pagination Footer */}
                  <div className="px-6 py-3 border-t border-slate-200 dark:border-slate-700 flex justify-between items-center">
                      <span className="text-sm text-slate-500">{t('patients_pagination_showing')} {treasuryPage} {t('patients_pagination_of')} {totalTreasuryPages || 1}</span>
                      <div className="flex gap-2">
                          <button onClick={() => setTreasuryPage(p => Math.max(1, p - 1))} disabled={treasuryPage === 1} className="p-1 rounded hover:bg-slate-100 disabled:opacity-50"><ChevronLeft size={16}/></button>
                          <button onClick={() => setTreasuryPage(p => Math.min(totalTreasuryPages, p + 1))} disabled={treasuryPage === totalTreasuryPages} className="p-1 rounded hover:bg-slate-100 disabled:opacity-50"><ChevronRight size={16}/></button>
                      </div>
                  </div>
              </Card>
          </div>
      )}

      {/* MODALS */}
      <Modal isOpen={isCreateModalOpen} onClose={() => setIsCreateModalOpen(false)} title={t('billing_modal_create_title')}>
        <form onSubmit={handleCreateSubmit} className="space-y-4">
          <Select 
            label={t('billing_modal_create_select_patient')}
            value={createForm.patientId}
            onChange={e => setCreateForm({...createForm, patientId: e.target.value})}
            required
          >
            <option value="">{t('billing_modal_create_choose_patient')}</option>
            {patients.map(p => <option key={p.id} value={p.id}>{p.fullName}</option>)}
          </Select>
          
          <div>
            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-1.5">{t('billing_modal_create_items_label')}</label>
            <div className="space-y-2 max-h-60 overflow-y-auto pr-1 custom-scrollbar">
              {createForm.items.map((item, index) => (
                <div key={index} className="flex flex-col sm:flex-row gap-2 items-start sm:items-center bg-slate-50 dark:bg-slate-900 p-2 rounded-lg">
                  {/* Catalog Selector */}
                  <select 
                    className="w-full sm:w-1/3 text-xs p-2 rounded border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800"
                    onChange={(e) => handleCatalogSelect(index, e.target.value)}
                    defaultValue=""
                  >
                    <option value="" disabled>{t('billing_modal_create_quick_add')}</option>
                    {catalogItems.map((c, i) => <option key={i} value={c.label}>{c.label}</option>)}
                  </select>

                  <Input 
                    placeholder={t('billing_modal_create_item_placeholder')}
                    value={item.description}
                    onChange={e => handleItemChange(index, 'description', e.target.value)}
                    className="flex-1"
                  />
                  <div className="flex gap-2 w-full sm:w-auto">
                    <Input 
                        placeholder="0.00"
                        type="number"
                        value={item.amount}
                        onChange={e => handleItemChange(index, 'amount', e.target.value)}
                        className="w-24"
                    />
                    <button type="button" onClick={() => handleRemoveItem(index)} className="text-red-500 hover:text-red-700 p-2">
                        <Trash2 size={16}/>
                    </button>
                  </div>
                </div>
              ))}
            </div>
            <Button size="sm" variant="secondary" onClick={handleAddItem} className="mt-2 w-full" icon={Plus}>{t('billing_modal_create_add_item_button')}</Button>
          </div>

          <div className="grid grid-cols-2 gap-4 border-t pt-4">
             <div>
                <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-1">{t('billing_modal_create_tax_rate')}</label>
                <select 
                    className="w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 p-2 text-sm"
                    value={createForm.selectedTaxId}
                    onChange={e => setCreateForm({...createForm, selectedTaxId: e.target.value})}
                >
                    <option value="">{t('billing_modal_create_none')}</option>
                    {taxRates.filter(t => t.isActive).map(t => (
                        <option key={t.id} value={t.id}>{language === 'ar' ? t.name_ar : t.name_en} ({t.rate}%)</option>
                    ))}
                </select>
             </div>
             <div className="text-right">
                <span className="block text-sm text-slate-500">{t('billing_modal_create_total_label')}</span>
                <span className="text-2xl font-bold text-slate-900 dark:text-white">
                    ${(() => {
                        const subtotal = createForm.items.reduce((sum, i) => sum + (parseFloat(i.amount) || 0), 0);
                        const taxRate = taxRates.find(t => t.id === parseInt(createForm.selectedTaxId));
                        const tax = taxRate ? (subtotal * taxRate.rate) / 100 : 0;
                        return (subtotal + tax).toFixed(2);
                    })()}
                </span>
             </div>
          </div>

          <div className="flex justify-end pt-4">
            <Button type="submit" disabled={isProcessing}>
                {isProcessing ? t('processing') : t('billing_modal_create_generate_button')}
            </Button>
          </div>
        </form>
      </Modal>

      {/* Advanced Payment Modal */}
      <Modal isOpen={isPaymentModalOpen} onClose={() => setIsPaymentModalOpen(false)} title={t('billing_modal_payment_title')}>
        {payingBill && (
          <form onSubmit={handlePaymentSubmit} className="space-y-6">
            <div className="text-center p-4 bg-slate-50 dark:bg-slate-900 rounded-xl">
              <p className="text-sm text-slate-500 dark:text-slate-400">{t('billing_modal_payment_balance_due')}</p>
              <p className="text-4xl font-bold text-slate-900 dark:text-white">${(payingBill.totalAmount - payingBill.paidAmount).toLocaleString()}</p>
            </div>
            
            <Select 
              label={t('billing_modal_payment_method')}
              value={paymentForm.method}
              onChange={e => setPaymentForm({...paymentForm, method: e.target.value})}
              required
            >
              {paymentMethods.length > 0 ? (
                  paymentMethods.filter(p => p.isActive).map(p => (
                      <option key={p.id} value={p.name_en}>{language === 'ar' ? p.name_ar : p.name_en}</option>
                  ))
              ) : (
                  <>
                    <option value="Cash">Cash</option>
                    <option value="Insurance">Insurance</option>
                  </>
              )}
            </Select>

            {/* Dynamic Fields based on Method */}
            <div className="space-y-4 animate-in fade-in">
                {/* 1. Cash: Amount & Notes only */}
                {paymentForm.method === 'Cash' && (
                    <>
                        <Input 
                            label={t('billing_modal_payment_amount')}
                            type="number" 
                            value={paymentForm.amount}
                            onChange={e => setPaymentForm({...paymentForm, amount: e.target.value})}
                            required
                        />
                        <Textarea 
                            label={t('patients_modal_action_notes')} 
                            rows={2} 
                            value={paymentForm.notes} 
                            onChange={e => setPaymentForm({...paymentForm, notes: e.target.value})} 
                        />
                    </>
                )}

                {/* 2. Insurance Specifics */}
                {paymentForm.method === 'Insurance' && (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-xl border border-blue-100 dark:border-blue-800">
                        <Input 
                            label={t('billing_modal_payment_amount')}
                            type="number" 
                            value={paymentForm.amount}
                            onChange={e => setPaymentForm({...paymentForm, amount: e.target.value})}
                            required
                            className="md:col-span-2"
                        />
                        <div className="md:col-span-2">
                            <Select 
                                label={t('patients_modal_form_insurance_provider')} 
                                value={paymentForm.insuranceProvider} 
                                onChange={e => setPaymentForm({...paymentForm, insuranceProvider: e.target.value})}
                                required
                            >
                                <option value="">{t('patients_modal_form_insurance_provider_select')}</option>
                                {insuranceProviders.map(p => <option key={p.id} value={p.name_en}>{language === 'ar' ? p.name_ar : p.name_en}</option>)}
                            </Select>
                        </div>
                        <Input 
                            label={t('patients_modal_form_insurance_policy')} 
                            value={paymentForm.policyNumber} 
                            onChange={e => setPaymentForm({...paymentForm, policyNumber: e.target.value})} 
                            required 
                        />
                        <Input 
                            label={t('patients_modal_form_insurance_expiry')} 
                            type="date" 
                            value={paymentForm.expiryDate} 
                            onChange={e => setPaymentForm({...paymentForm, expiryDate: e.target.value})} 
                            required 
                        />
                        <div className="md:col-span-2">
                            <Textarea 
                                label={t('patients_modal_form_insurance_notes')} 
                                rows={2} 
                                value={paymentForm.notes} 
                                onChange={e => setPaymentForm({...paymentForm, notes: e.target.value})} 
                            />
                        </div>
                    </div>
                )}

                {/* 3. Bank/Card/Other Specifics */}
                {paymentForm.method !== 'Cash' && paymentForm.method !== 'Insurance' && (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 p-4 bg-slate-50 dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-700">
                        <Input 
                            label={t('billing_modal_payment_amount')}
                            type="number" 
                            value={paymentForm.amount}
                            onChange={e => setPaymentForm({...paymentForm, amount: e.target.value})}
                            required
                            className="md:col-span-2"
                        />
                        <Input 
                            label={t('billing_modal_payment_ref')} 
                            value={paymentForm.transactionId} 
                            onChange={e => setPaymentForm({...paymentForm, transactionId: e.target.value})} 
                            required 
                        />
                        <Input 
                            label={t('date')} 
                            type="date" 
                            value={paymentForm.date} 
                            onChange={e => setPaymentForm({...paymentForm, date: e.target.value})} 
                            required 
                        />
                        <div className="md:col-span-2">
                            <Textarea 
                                label={t('patients_modal_action_notes')} 
                                rows={2} 
                                value={paymentForm.notes} 
                                onChange={e => setPaymentForm({...paymentForm, notes: e.target.value})} 
                            />
                        </div>
                    </div>
                )}
            </div>

            <div className="flex justify-end pt-4">
              <Button type="submit" icon={isProcessing ? undefined : CheckCircle} disabled={isProcessing}>
                  {isProcessing ? t('processing') : t('billing_modal_payment_confirm_button')}
              </Button>
            </div>
          </form>
        )}
      </Modal>

      {/* Refund Modal */}
      <Modal isOpen={isRefundModalOpen} onClose={() => setIsRefundModalOpen(false)} title={t('billing_modal_refund_title')}>
        {refundingBill && (
            <form onSubmit={handleRefundSubmit} className="space-y-4">
                <div className="bg-red-50 dark:bg-red-900/20 p-4 rounded-xl border border-red-100 dark:border-red-900/50">
                    <div className="flex items-center gap-3 mb-2">
                        <RefreshCcw className="text-red-600" size={20}/>
                        <p className="text-sm text-red-800 dark:text-red-300 font-bold">{t('billing_modal_refund_subtitle', {billNumber: refundingBill.billNumber})}</p>
                    </div>
                    <div className="flex justify-between text-xs text-red-600 dark:text-red-400">
                        <span>{t('billing_modal_refund_total_paid')}: ${refundingBill.paidAmount}</span>
                        <span>{t('billing_modal_refund_max')}: ${refundingBill.paidAmount}</span>
                    </div>
                </div>
                
                <div className="grid grid-cols-2 gap-4">
                    <Input 
                        label={t('billing_modal_refund_amount')} 
                        type="number" 
                        max={refundingBill.paidAmount}
                        value={refundForm.amount}
                        onChange={e => setRefundForm({...refundForm, amount: e.target.value})}
                        required
                    />
                    <Select 
                        label={t('billing_modal_refund_method')}
                        value={refundForm.method}
                        onChange={e => setRefundForm({...refundForm, method: e.target.value})}
                    >
                        <option value="Cash">Cash</option>
                        <option value="Bank Transfer">Bank Transfer</option>
                        <option value="Credit Card Reversal">Credit Card Reversal</option>
                        <option value="Check">Check</option>
                    </Select>
                </div>

                <Select 
                    label={t('billing_modal_refund_reason')} 
                    value={refundForm.reason}
                    onChange={e => setRefundForm({...refundForm, reason: e.target.value})}
                    required
                >
                    <option value="Service Cancelled">{t('billing_modal_refund_reason_service')}</option>
                    <option value="Overcharged">{t('billing_modal_refund_reason_overcharged')}</option>
                    <option value="Duplicate Payment">{t('billing_modal_refund_reason_duplicate')}</option>
                    <option value="Customer Satisfaction">{t('billing_modal_refund_reason_satisfaction')}</option>
                    <option value="Other">{t('billing_modal_refund_reason_other')}</option>
                </Select>

                {refundForm.reason === 'Other' && (
                    <Textarea 
                        label={t('billing_modal_refund_custom_reason')} 
                        value={refundForm.customReason}
                        onChange={e => setRefundForm({...refundForm, customReason: e.target.value})}
                        required
                        rows={2}
                    />
                )}

                <div className="flex justify-end pt-4 gap-2">
                    <Button type="button" variant="secondary" onClick={() => setIsRefundModalOpen(false)}>{t('cancel')}</Button>
                    <Button type="submit" variant="danger" disabled={isProcessing}>
                        {isProcessing ? t('processing') : t('billing_modal_refund_confirm')}
                    </Button>
                </div>
            </form>
        )}
      </Modal>

      {/* Expense Modal */}
      <Modal isOpen={isExpenseModalOpen} onClose={() => setIsExpenseModalOpen(false)} title={t('billing_modal_expense_title')}>
          <form onSubmit={handleExpenseSubmit} className="space-y-4">
              <Select label={t('billing_modal_expense_category')} value={expenseForm.category} onChange={e => setExpenseForm({...expenseForm, category: e.target.value})}>
                  <option value="General">{t('billing_modal_expense_cat_general')}</option>
                  <option value="Supplies">{t('billing_modal_expense_cat_supplies')}</option>
                  <option value="Maintenance">{t('billing_modal_expense_cat_maintenance')}</option>
                  <option value="Utilities">{t('billing_modal_expense_cat_utilities')}</option>
                  <option value="Salary">{t('billing_modal_expense_cat_salary')}</option>
                  <option value="Equipment">{t('billing_modal_expense_cat_equipment')}</option>
              </Select>
              <Input label={t('billing_modal_expense_amount')} type="number" required value={expenseForm.amount} onChange={e => setExpenseForm({...expenseForm, amount: e.target.value})} />
              <div className="grid grid-cols-2 gap-4">
                  <Select label={t('billing_modal_expense_method')} value={expenseForm.method} onChange={e => setExpenseForm({...expenseForm, method: e.target.value})}>
                      <option value="Cash">Cash</option>
                      <option value="Bank Transfer">Bank Transfer</option>
                      <option value="Check">Check</option>
                  </Select>
                  <Input label={t('date')} type="date" required value={expenseForm.date} onChange={e => setExpenseForm({...expenseForm, date: e.target.value})} />
              </div>
              <Textarea label={t('billing_modal_expense_description')} required rows={3} value={expenseForm.description} onChange={e => setExpenseForm({...expenseForm, description: e.target.value})} />
              <div className="flex justify-end pt-4 gap-3">
                  <Button type="button" variant="secondary" onClick={() => setIsExpenseModalOpen(false)}>{t('cancel')}</Button>
                  <Button type="submit" disabled={isProcessing}>
                      {isProcessing ? t('processing') : t('billing_modal_expense_save')}
                  </Button>
              </div>
          </form>
      </Modal>

      <Modal isOpen={!!selectedBill} onClose={() => setSelectedBill(null)} title={t('billing_modal_preview_title')}>
        {selectedBill && (
          <div>
            <InvoiceView bill={selectedBill} />
            <div className="mt-6 flex justify-end gap-3">
              <Button variant="secondary" onClick={() => setSelectedBill(null)}>{t('close')}</Button>
              <Button icon={Printer}>{t('billing_modal_preview_print_button')}</Button>
            </div>
          </div>
        )}
      </Modal>

      {/* Confirmation Dialog for Service Cancellation */}
      <ConfirmationDialog 
        isOpen={confirmState.isOpen}
        onClose={() => setConfirmState({ ...confirmState, isOpen: false })}
        onConfirm={confirmState.action}
        title={confirmState.title}
        message={confirmState.message}
        type={confirmState.type}
      />

    </div>
  );
};
